---
# tasks file for nodejs

- name: Add NodeSource GPG key
  ansible.builtin.apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present
  become: true

- name: Add NodeSource apt repository for Node.js {{ nodejs_version }}
  ansible.builtin.apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_lsb.codename }} main"
    state: present
    filename: nodesource
  become: true

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true

- name: Install Node.js and npm
  ansible.builtin.apt:
    name: nodejs
    state: present
  become: true

- name: Verify Node.js installation
  ansible.builtin.command:
    cmd: node -v
  register: node_version
  changed_when: false

- name: Display installed Node.js version
  ansible.builtin.debug:
    msg: "Installed Node.js version: {{ node_version.stdout }}"

- name: Include ExpressJS deployment tasks
  include_tasks: expressjs.yml