---
# handlers file for nodejs

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes
  become: true
  ignore_errors: true

- name: Restart Express App
  ansible.builtin.systemd:
    name: "{{ app_name }}"
    state: restarted
    no_block: yes
  become: true